baseURL = "https://www.bouldergearlab.com/"
title = "Boulder Gear Lab"
theme = "hugo-universal-theme"
languageCode = "en-us"
defaultContentLanguage = "en"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content
summaryLength = 70

[params]
    viewMorePostLink = "/reviews/"
    author = "Your Name"
    defaultKeywords = ["gear reviews", "outdoor equipment", "running gear"]
    mainSections = ["reviews"]
    defaultDescription = "In-depth gear reviews and outdoor equipment analysis"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "" # the Twitter handle of your site (without the '@')
    youtube = "https://youtube.com/@yourchannel"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = ""
    contact_form_ajax = false

    about_us = "<p>Boulder Gear Lab provides in-depth, honest reviews of outdoor gear and running equipment.</p>"
    copyright = "Copyright (c) 2024, Boulder Gear Lab; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Boulder Gear Lab"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Boulder Gear Lab</strong>
        <br>Colorado
        <br>
        <strong>USA</strong>
      </p>
      """

[Permalinks]
    reviews = "/reviews/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">In-depth gear reviews and outdoor equipment analysis</p>
      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:hello@bouldergearlab.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousels]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    title = "Testimonials"
    subtitle = "What our readers say"

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Check out our latest reviews"
    subtitle = "Honest, in-depth gear analysis"
    link_url = "/reviews/"
    link_text = "View all reviews"

[params.clients]
    enable = false

[params.recent_posts]
    enable = true
    title = "Latest Reviews"
    subtitle = "Fresh off the trail"
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Reviews"
    identifier = "menu.reviews"
    url        = "/reviews/"
    weight     = 2

[[menu.main]]
    name       = "Road Trail Run"
    identifier = "menu.roadtrailrun"
    url        = "/roadtrailrun/"
    weight     = 3

[[menu.main]]
    name       = "About"
    identifier = "menu.about"
    url        = "/about/"
    weight     = 4

[[menu.main]]
    name       = "Contact"
    identifier = "menu.contact"
    url        = "/contact/"
    weight     = 5